package com.example.contesttracker

import retrofit2.http.GET
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory

interface ClistApiService {
    @GET("contests.json")
    suspend fun getUpcomingContests(): ContestResponse
}

object RetrofitClient {
    // Public, credential-free feed generated by .github/workflows/refresh-contests.yml.
    const val BASE_URL = "https://dhruv-1309.github.io/CodeCountdown/"

    val apiService: ClistApiService by lazy {
        Retrofit.Builder()
            .baseUrl(BASE_URL)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(ClistApiService::class.java)
    }
}
